apiVersion: v1
kind: Service
metadata:
  name: smolsqls-headless
  namespace: smolsqls
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: smolsqls
  ports:
    - name: epmd
      port: 4369
    - name: erl-dist
      port: 9100
    - name: gen-rpc
      port: 5369
    - name: gen-rpc-tls
      port: 5870
---
apiVersion: v1
kind: Service
metadata:
  name: smolsqls
  namespace: smolsqls
spec:
  selector:
    app: smolsqls
  ports:
    - name: http
      port: 80
      targetPort: 4000
