apiVersion: v1
kind: Service
metadata:
  name: smolsqls-external
  namespace: smolsqls
spec:
  type: NodePort
  selector:
    app: smolsqls
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30080
