apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - minio.yaml
  - external-service.yaml
  - sqlite-nodes.yaml

patches:
  - path: resources-patch.yaml
  - path: operator-patch.yaml

images:
  - name: smolsqls
    newTag: dev
  - name: smolsqls-operator
    newTag: dev

secretGenerator:
  - name: smolsqls-env
    namespace: smolsqls
    literals:
      - DATABASE_URL=ecto://postgres:postgres@postgres/smolsqls
      - SECRET_KEY_BASE=kind-only-not-a-secret-kind-only-not-a-secret-kind-only-not-a-secret
      - RELEASE_COOKIE=kind-only-cookie
      - PHX_HOST=localhost
      - PHX_URL_PORT=4000
      - PHX_URL_SCHEME=http
      - S3_ACCESS_KEY_ID=smolsqls
      - S3_SECRET_ACCESS_KEY=smolsqls-secret
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=smolsqls-replica
      - LITESTREAM_REPLICA_URL_PREFIX=s3://smolsqls-replica.minio:9000/litestream
      - GEN_RPC_TLS=true
      - DIST_TLS=true

  - name: smolsqls-gen-rpc-tls
    namespace: smolsqls
    files:
      - tls/ca.pem
      - tls/smolsqls-0.pem
      - tls/smolsqls-0.key
      - tls/smolsqls-1.pem
      - tls/smolsqls-1.key
      - tls/smolsqls-2.pem
      - tls/smolsqls-2.key

generatorOptions:
  disableNameSuffixHash: true
