apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - minio.yaml
  - external-service.yaml
  - sqlite-nodes.yaml

patches:
  - path: resources-patch.yaml

images:
  - name: sqlites
    newTag: dev
  - name: sqlites-operator
    newTag: dev

secretGenerator:
  - name: sqlites-env
    namespace: sqlites
    literals:
      - DATABASE_URL=ecto://postgres:postgres@postgres/sqlites
      - SECRET_KEY_BASE=kind-only-not-a-secret-kind-only-not-a-secret-kind-only-not-a-secret
      - RELEASE_COOKIE=kind-only-cookie
      - PHX_HOST=localhost
      - PHX_URL_PORT=4000
      - PHX_URL_SCHEME=http
      - S3_ACCESS_KEY_ID=sqlites
      - S3_SECRET_ACCESS_KEY=sqlites-secret
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=sqlites-replica
      - LITESTREAM_REPLICA_URL_PREFIX=s3://sqlites-replica.minio:9000/litestream

generatorOptions:
  disableNameSuffixHash: true
