apiVersion: apps/v1
kind: Deployment
metadata:
  name: smolsqls-operator
  namespace: smolsqls
spec:
  template:
    spec:
      containers:
        - name: smolsqls-operator
          env:
            - name: AUTO_EVACUATE_WINDOW_SECONDS
              value: "30"
