apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlites-operator
  namespace: sqlites
spec:
  template:
    spec:
      containers:
        - name: sqlites-operator
          env:
            - name: AUTO_EVACUATE_WINDOW_SECONDS
              value: "30"
