apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smolsqls
  namespace: smolsqls
spec:
  podManagementPolicy: OrderedReady
  template:
    spec:
      containers:
        - name: smolsqls
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        - name: litestream
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
