apiVersion: sqlites.supabase.com/v1alpha1
kind: SqliteNode
metadata:
  name: sqlites-0
  namespace: sqlites
spec:
  ordinal: 0
  erlangNode: sqlites@sqlites-0.sqlites-headless.sqlites.svc.cluster.local
  litestream:
    bucket: s3://sqlites-replica
    pathPrefix: node-0/
---
apiVersion: sqlites.supabase.com/v1alpha1
kind: SqliteNode
metadata:
  name: sqlites-1
  namespace: sqlites
spec:
  ordinal: 1
  erlangNode: sqlites@sqlites-1.sqlites-headless.sqlites.svc.cluster.local
  litestream:
    bucket: s3://sqlites-replica
    pathPrefix: node-1/
---
apiVersion: sqlites.supabase.com/v1alpha1
kind: SqliteNode
metadata:
  name: sqlites-2
  namespace: sqlites
spec:
  ordinal: 2
  erlangNode: sqlites@sqlites-2.sqlites-headless.sqlites.svc.cluster.local
  litestream:
    bucket: s3://sqlites-replica
    pathPrefix: node-2/
