apiVersion: smolsqls.supabase.com/v1alpha1
kind: SqliteNode
metadata:
  name: smolsqls-0
  namespace: smolsqls
spec:
  ordinal: 0
  erlangNode: smolsqls@smolsqls-0.smolsqls-headless.smolsqls.svc.cluster.local
  litestream:
    bucket: s3://smolsqls-replica
    pathPrefix: node-0/
---
apiVersion: smolsqls.supabase.com/v1alpha1
kind: SqliteNode
metadata:
  name: smolsqls-1
  namespace: smolsqls
spec:
  ordinal: 1
  erlangNode: smolsqls@smolsqls-1.smolsqls-headless.smolsqls.svc.cluster.local
  litestream:
    bucket: s3://smolsqls-replica
    pathPrefix: node-1/
---
apiVersion: smolsqls.supabase.com/v1alpha1
kind: SqliteNode
metadata:
  name: smolsqls-2
  namespace: smolsqls
spec:
  ordinal: 2
  erlangNode: smolsqls@smolsqls-2.smolsqls-headless.smolsqls.svc.cluster.local
  litestream:
    bucket: s3://smolsqls-replica
    pathPrefix: node-2/
